---
title: "navon_prism_mem_v5"
output: html_document
---


```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

```{r, fig.width=7.5, fig.height=5}

# Library Packages
library(ggplot2)
library(lmerTest)
library(lme4)
library(emmeans)
library(interactions)
library(car)
library(MASS)
library(sjPlot)
library(brms)
library(glmmTMB)
library(dplyr)
library(Hmisc)

### Navon RT Models
navon_struct_prism <- read.csv('/Volumes/823777_TNI_DP5_Healthy/PRISM_pilot/Navon_Behavioral_LongFormat_PRISM_final_x4_z_day.csv',fileEncoding="UTF-8-BOM")


#Correct Trials
navon_struct_prism_cor <- navon_struct_prism[which(navon_struct_prism$correct=='1'),] 

# Threshold RT
navon_struct_prism_cor <- navon_struct_prism_cor[which(navon_struct_prism_cor$RT>.2),]
navon_struct_prism_cor <- navon_struct_prism_cor[which(navon_struct_prism_cor$RT<1.5),]

navon_struct_prism_cor2 <- navon_struct_prism_cor

# Mean center data
navon_struct_prism_cor2$Timepoint <- relevel(factor(navon_struct_prism_cor2$Timepoint), ref="pre")
navon_struct_prism_cor2$Stimulation_Site <- relevel(factor(navon_struct_prism_cor2$Stimulation_Site), ref="Vertex")
navon_struct_prism_cor2$Task_Low_High <- relevel(factor(navon_struct_prism_cor2$Task_Low_High), ref="low")


navonpre <- navon_struct_prism_cor2[which(navon_struct_prism_cor2$Timepoint == "pre"),]
 
emm_options(lmerTest.limit = 29710)
emm_options(pbkrtest.limit = 29710)

## Navon models with session number as a continuous
## Two way
fitnavonp <- lmer(log(RT)~ Stimulation_Site*Timepoint+Days+(1+Days| Subj:Timepoint), data=navon_struct_prism_cor2, control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=100000)), REML=F)
tabnavonp <- tab_model(fitnavonp, show.intercept = TRUE, show.est = TRUE, show.ci = FALSE, show.se = TRUE, show.stat = TRUE, show.p = TRUE, string.se = "SE",string.stat= "t-value", pred.labels = c('Intercept', 'Stimulation Site [DAN]', 'Stimulation Site [FPCN-B]', 'Timepoint [Post]', 'Days', 'Stimulation Site [DAN] * Timepoint [Post]', 'Stimulation Site [FPCN-B] * Timepoint [Post]'))
summary(fitnavonp)
vif(fitnavonp)

stim_siteLabs <- c('Vertex', 'DAN', 'FPCN-B')
names(stim_siteLabs) <- c('vertex', 'DAN', 'FPCNB')
timepoint_Labs <- c('Pre', 'Post')
names(timepoint_Labs) <- c('pre', 'post')
navon_Labs <- c('Low', 'High')
names(navon_Labs) <- c('low', 'high')
cbPalette <- c('#999999', '#009E73', '#E69F00', '#F0E442', '#0072B2', '#D55E00', '#CC79A7')

emmTimeCogSess_TimeCog <- emmeans(fitnavonp, ~ Stimulation_Site| Timepoint, param = 'logk')
acc3Way_TimeCog <- as.data.frame(emmTimeCogSess_TimeCog)
data_labels <- c(Stimulation_Site ="Stimulation_Site", Timepoint= "Timepoint", emmean = "emmean", SE="SE", df="df",lower.CL="lower.CL", upper.CL="upper.CL")
label(acc3Way_TimeCog) <- as.list(data_labels[match(names(acc3Way_TimeCog),names(data_labels))])

ggplot(acc3Way_TimeCog, aes(x = Stimulation_Site, y = emmean, color = Stimulation_Site)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(width = .5, size=1.5,aes(ymin = lower.CL, ymax = upper.CL)) +
  theme_bw() +
  theme(text = element_text(size = 15), plot.title = element_text(hjust = .5, margin = margin(b = 15)), plot.subtitle = element_text(hjust = .5), strip.background = element_blank(), axis.title.x = element_text(margin = margin(t = 10)), axis.title.y = element_text(margin = margin(r = 20))) +
  xlab(label = 'Stimulation Site') +
  ylab(label = 'Predicted log(RT)') +
  labs(title= 'TMS Effect on Navon Response Times') +
  labs(subtitle = 'Time Point', color = 'Stimulation Site') +
  scale_x_discrete(labels = stim_siteLabs) +
  ylim(-0.9, 0)+
  scale_colour_manual(values=cbPalette, labels = stim_siteLabs) +
  facet_grid(. ~ Timepoint, labeller = labeller(Timepoint = timepoint_Labs))
#labs(caption= "Bracketed terms are in comparison to the reference conditions. Stimulation Site in reference to Vertex. Timepoint in reference to Pre. Task Condition in reference to low.")


## Three way 
fitnavonptask <- lmer(log(RT)~ Stimulation_Site*Timepoint*Task_Low_High+ Days + (1 + Days|Subj:Timepoint), data=navon_struct_prism_cor2, control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=100000)),REML=F)
tab_model(fitnavonptask, show.intercept = TRUE, show.est = TRUE, show.ci = FALSE, show.se = TRUE, show.p = TRUE, string.se = "SE", pred.labels = c('Intercept', 'Stimulation Site [DAN]', 'Stimulation Site [FPCN-B]', 'Timepoint [Post]', 'Task Condition [High]', 'Days', 'Stimulation Site [DAN] * Timepoint [Post]', 'Stimulation Site [FPCN-B] * Timepoint [Post]', 'Stimulation Site [DAN] * Task Condition [High]', 'Stimulation Site [FPCN-B] * Task Condition [High]', 'Timepoint [Post] * Task Condition [High]', 'Stimulation Site [DAN] * Timepoint [Post] * Task Condition [High]', 'Stimulation Site [FPCN-B] * Timepoint [Post] * Task Condition [High]'))
summary(fitnavonptask)
vif(fitnavonptask)

emmTimeCogSess_TimeCogn <- emmeans(fitnavonptask, ~ Stimulation_Site| Timepoint * Task_Low_High, param = 'logk')
acc3Way_TimeCogn <- as.data.frame(emmTimeCogSess_TimeCogn)
data_labelsa <- c(Stimulation_Site ="Stimulation_Site", Timepoint= "Timepoint", emmean = "emmean", SE="SE", df="df",lower.CL="lower.CL", upper.CL="upper.CL")
label(acc3Way_TimeCogn) <- as.list(data_labelsa[match(names(acc3Way_TimeCogn),names(data_labelsa))])
ggplot(acc3Way_TimeCogn, aes(x = Stimulation_Site, y = emmean, color = Stimulation_Site)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(width = .3, size=1.5,aes(ymin = lower.CL, ymax = upper.CL)) +
  theme_bw() +
  theme(text = element_text(size = 15), plot.title = element_text(hjust = .5, margin = margin(b = 15)), plot.subtitle = element_text(hjust = .5), strip.background = element_blank(), axis.title.x = element_text(margin = margin(t = 10)), axis.title.y = element_text(margin = margin(r = 20))) +
  xlab(label = 'Stimulation Site') +
  ylab(label = 'Predicted log(RT)') +
  #labs(title= 'Cognitive Control Effect on Navon Response Times')+
  theme(plot.title= element_text(hjust=0.5)) + labs(subtitle = 'Time Point', color = 'Stimulation Site') +
  scale_x_discrete(labels = stim_siteLabs) +
  scale_colour_manual(values=cbPalette, labels = stim_siteLabs) +
  scale_fill_discrete(name='Stimulation Site') +
  facet_grid(Task_Low_High ~ Timepoint, labeller = labeller(Timepoint = timepoint_Labs,Task_Low_High = navon_Labs)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = 'Task Condition', breaks = NULL, labels = navon_Labs)) 



# Contrast Pre-Stimulation load effects on RT
navonrtstimload <- pairs(emmeans(fitnavonptask, ~ Task_Low_High | Timepoint))

# Contrast Practice effects on RT (average pre-post effect in Vertex condition)
navonrtvertexcond <- pairs(emmeans(fitnavonptask, ~ Timepoint | Stimulation_Site, ))

# Contrast The TMS effect on overall performance for (i) DAN and (ii) FPCN-B relative to (iii) Vertex for RT
navonrtoverall <- pairs(emmeans(fitnavonptask, ~ Stimulation_Site*Timepoint))

# Contrast The TMS effect on performance in each load condition
navonrtloadcond <- pairs(emmeans(fitnavonptask, ~ Timepoint | Stimulation_Site*Task_Low_High))

#contrasts of contrasts of contrasts for pre-post TMS for task load for stimulation site
TimeCogSessContrastsThreeWay <- emmeans(fitnavonptask, pairwise ~ Timepoint* Stimulation_Site * Task_Low_High, param = 'logk')
contrast(TimeCogSessContrastsThreeWay[[1]], interaction = c(Task_Low_High = 'revpairwise'))

### Navon Accuracy Models
navonacp <- navon_struct_prism[which(navon_struct_prism$RT>.2),]
navonacp <- navon_struct_prism[which(navon_struct_prism$RT<1.5),]
navonacp$Timepoint <- relevel(factor(navonacp$Timepoint), ref="pre")
navonacp$Stimulation_Site <- relevel(factor(navonacp$Stimulation_Site), ref="Vertex")
navonacp$Task_Low_High <- relevel(factor(navonacp$Task_Low_High), ref="low")


## Two way 
fitnavonacp <- glmer(correct ~ Timepoint*Stimulation_Site + Days +(1+Days| Subj:Timepoint), family="binomial", data=navonacp)
tab_model(fitnavonacp)
summary(fitnavonacp)
vif(fitnavonacp)


emmTimeCogSess_TimeCognp <- emmeans(fitnavonacp, ~ Stimulation_Site| Timepoint, param = 'logk')
acc3Way_TimeCognp <- as.data.frame(emmTimeCogSess_TimeCognp)
data_labelsap <- c(Stimulation_Site ="Stimulation_Site", Timepoint= "Timepoint", emmean = "emmean", SE="SE", df="df",asymp.LCL="asymp.LCL", asymp.UCL="asymp.UCL")
label(acc3Way_TimeCognp) <- as.list(data_labelsap[match(names(acc3Way_TimeCognp),names(data_labelsap))])
ggplot(acc3Way_TimeCognp, aes(x = Stimulation_Site, y = emmean, color = Stimulation_Site)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(width = .5, size=1.5,aes(ymin = asymp.LCL, ymax = asymp.UCL)) +
  theme_bw() +
  theme(text = element_text(size = 15), plot.title = element_text(hjust = .5, margin = margin(b = 15)), plot.subtitle = element_text(hjust = .5), strip.background = element_blank(), axis.title.x = element_text(margin = margin(t = 10)), axis.title.y = element_text(margin = margin(r = 20))) +
  xlab(label = 'Stimulation Site') +
  ylab(label = 'Predicted Accuracy') +
  labs(title= 'Navon TMS Effect on Accuracy') +
  labs(subtitle = 'Time Point', color = 'Stimulation Site') +
  scale_x_discrete(labels = stim_siteLabs) +
  scale_colour_manual(values=cbPalette, labels = stim_siteLabs) +
  facet_grid(. ~ Timepoint, labeller = labeller(Timepoint = timepoint_Labs)) 
  

## Three way 
fitnavonacptask <- glmer(correct ~ Timepoint*Stimulation_Site*Task_Low_High + Days + (1 + Days| Subj:Timepoint), family="binomial", data=navonacp,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=100000)))
tab_model(fitnavonacptask, show.intercept = TRUE, show.est = TRUE, show.ci = FALSE, show.se = TRUE, show.p = TRUE, string.se = "SE", pred.labels = c('Intercept', 'Stimulation Site [DAN]', 'Stimulation Site [FPCN-B]', 'Timepoint [Post]', 'Task Condition [High]', 'Days', 'Stimulation Site [DAN] * Timepoint [Post]', 'Stimulation Site [FPCN-B] * Timepoint [Post]', 'Stimulation Site [DAN] * Task Condition [High]', 'Stimulation Site [FPCN-B] * Task Condition [High]', 'Timepoint [Post] * Task Condition [High]', 'Stimulation Site [DAN] * Timepoint [Post] * Task Condition [High]', 'Stimulation Site [FPCN-B] * Timepoint [Post] * Task Condition [High]'))
summary(fitnavonacptask)
vif(fitnavonacptask)

emmTimeCogSess_TimeCogac <- emmeans(fitnavonacptask, ~ Stimulation_Site| Timepoint * Task_Low_High, param = 'logk')
acc3Way_TimeCogac <- as.data.frame(emmTimeCogSess_TimeCogac)
data_labelsac <- c(Stimulation_Site ="Stimulation_Site", Timepoint= "Timepoint", emmean = "emmean", SE="SE", df="df",asymp.LCL="asymp.LCL", asymp.UCL="asymp.UCL")
label(acc3Way_TimeCogac) <- as.list(data_labelsac[match(names(acc3Way_TimeCogac),names(data_labelsac))])
ggplot(acc3Way_TimeCogac, aes(x = Stimulation_Site, y = emmean, color = Stimulation_Site)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(width = .3, size=1.5,aes(ymin = asymp.LCL, ymax=asymp.UCL)) +
  theme_bw() +
  theme(text = element_text(size = 15), plot.title = element_text(hjust = .5, margin = margin(b = 15)), plot.subtitle = element_text(hjust = .5), strip.background = element_blank(), axis.title.x = element_text(margin = margin(t = 10)), axis.title.y = element_text(margin = margin(r = 20))) +
  xlab(label = 'Stimulation Site') +
  ylab(label = 'Predicted Accuracy') +
 # labs(title= 'Cognitive Control Effect on Navon Accuracy')+
  labs(subtitle = 'Time Point', color = 'Stimulation Site') +
  scale_x_discrete(labels = stim_siteLabs) +
  scale_colour_manual(values=cbPalette, labels = stim_siteLabs) +
  scale_fill_discrete(name='Stimulation Site') +
  facet_grid(Task_Low_High ~ Timepoint, labeller = labeller(Timepoint = timepoint_Labs,Task_Low_High = navon_Labs)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = 'Task Condition', breaks = NULL, labels = navon_Labs))

ggplot(acc3Way_TimeCog, aes(x = stim_site, y = emmean, color =stim_site)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(width = .3, size=1.5,aes(ymin = asymp.LCL, ymax=asymp.UCL)) +
  theme_bw() +
  theme(text = element_text(size = 15), plot.title = element_text(hjust = .5, margin = margin(b = 15)), plot.subtitle = element_text(hjust = .5), strip.background = element_blank(), axis.title.x = element_text(margin = margin(t = 10)), axis.title.y = element_text(margin = margin(r = 20))) +
  xlab(label = 'Stimulation Site') +
  ylab(label = 'Predicted Accuracy') +
 # labs(title= 'Cognitive Control Effect on N-back Accuracy')+
  labs(subtitle = 'Time Point', color = 'Stimulation Site') +
  scale_x_discrete(labels = stim_siteLabs) +
  scale_colour_manual(values=cbPalette, labels = stim_siteLabs) +
  scale_fill_discrete(name='Stimulation Site') +
  facet_grid(n_back ~ timepoint, labeller = labeller(timepoint = timepoint_Labs,n_back = nBack_Labs)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = 'Task Condition', breaks = NULL, labels = nBack_Labs))

# Contrast Pre-Stimulation load effects on accuracy
pairs(emmeans(fitnavonacptask, ~ Task_Low_High | Timepoint))

# Contrast Practice effects on accuracy (average pre-post effect in Vertex condition)
pairs(emmeans(fitnavonacptask, ~ Timepoint | Stimulation_Site))

# Contrast The TMS effect on overall performancer for (i) DAN and (ii) FPCN-B relative to (iii) Vertex for accuracy
pairs(emmeans(fitnavonacptask, ~ Stimulation_Site*Timepoint))

# Contrast The TMS effect on performance in each load condition
pairs(emmeans(fitnavonacptask, ~ Timepoint | Stimulation_Site*Task_Low_High))

#contrasts of contrasts of contrasts for pre-post TMS for task load for stimulation site
TimeCogSessContrastsThreeWay <- emmeans(fitnavonacptask, pairwise ~ Timepoint* Stimulation_Site * Task_Low_High, param = 'logk')
contrast(TimeCogSessContrastsThreeWay[[1]], interaction = c(Task_Low_High = 'revpairwise'))

```
